### ISSUE TITLE
clhs - minimum distance not working 

### ISSUE THREAD

**Issue by gcperk** [bcgov/PEMsamplr#5]
clhs is not placing points at minimum distance in small test area. I corrected a missing [parameter](https://github.com/bcgov/PEMsamplr/commit/3eddb180295eb0e02a5b1d8ff888ffecfafb8033), and rerun but does not seem to have fixed the problem. 

I added a clhs old version as a placeholder in the mean time.

**Comment by kdaust** [comment]
I think I've fixed this - added the distance to the clhs objective function. Could you test it and see how it goes? I found it worked well up to 800 meter spacing; sometimes failed with 1 km spacing. Also, it seems to require more iterations - I found 20000 generally worked well.

**Comment by gcperk** [comment]
Hey @kdaust  - i downloaded new clhs package (from your repo) and re-ran it. It is better, but still not working for minimum distance. 
![image](https://user-images.githubusercontent.com/39040813/209699933-2fffaa8c-f780-4aeb-8cdd-eee611f5987b.png)
Here is two clhs sets of a 10 site/ 2 slice example. The highlighted points are 300m apart and belong to the purple clhs run. I tried bumping up the iter to 1000,000 but still producing many points that are closer than the 1000m specified.  

Do you think there is a way to fix this? or do we need to add some more brute force method, where i continually reran the clhs until they were all more than min distance apart?

**Comment by kdaust** [comment]
Hi @gcperk - ok I'm pretty sure it's working properly now. I've made changes to the create_clhs.R script (to check distance and rerun if necessary - usually not), but most importantly, I found a bug in the clhs package, where the indexing was off any time must.include was used. It's been fixed, so make sure you rebuild the package. I've tested with the data you sent and it seems to be working well now.

**Comment by gcperk** [comment]
Thanks @kdaust ! I was just testing it and it is certainly better! I did notice it is not maintaining the set the distance all the time... which is probably ok given the constraints. I did test with a 1200m min distance and it did some really weird points so perhaps there is still a bug? 

In the image shows the cost surface and excluded areas (orange). The hot pink are 10 clhs points with 1000m min distance (the closest points are in the center - about 600m apart. 

The light pink and green are 10 clhs 1200m apart although they are being places on top of each other in clumps? 

![image](https://user-images.githubusercontent.com/39040813/211628668-0f829290-1fe3-4835-9e74-05307d69cfff.png)

**Comment by gcperk** [comment]
Hey @kdaust 
Thanks for the updates on the clhs min distance package. I like the updates with message and text to rerun feature. FYI there is still some minor issues where points are placed within specified min distance: The example below shows 1km buffers on each point. The minimum difference is about 550m which is ok for now but we should fix this down the track. 
Thanks for your work on this!

![image](https://user-images.githubusercontent.com/39040813/226189850-97517298-a3f9-45b0-a809-011c706752db.png)
